version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=admin
    networks:
      - compose-net
    expose:
      - 3306
networks:
  compose-net:
    driver: bridge
